version: '3.7'

services:
    postgres:
        image: 'postgres:11.1-alpine'
        ports: ['5432:5432']
        environment:
            - POSTGRES_DB=event-store
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - TZ=Europe/Berlin

    mysql:
        image: 'mysql:8.0.18'
        command: --default-authentication-plugin=mysql_native_password
        ports: ['3306:3306']
        environment:
            - MYSQL_DATABASE=event-store
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - TZ=Europe/Berlin
